version: "3.9"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: dev.env
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    env_file: dev.env
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: ./
      dockerfile: celery.dev.Dockerfile
    command: celery -A backend worker -l info
    volumes:
      - ./:/code
    env_file: dev.env
    depends_on:
      - redis
      - db

  #  celery_beat:
  #    restart: always
  #    build:
  #      context: ./
  #      dockerfile: celery.dev.Dockerfile
  #    command: celery -A backend beat -l info
  #    volumes:
  #      - ./:/code
  #    env_file: dev.env
  #    depends_on:
  #      - celery

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis