# Generated by Django 4.2 on 2025-03-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('event_type', models.CharField(choices=[], max_length=50)),
                ('is_conditional', models.BooleanField(default=False)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('has_time_offset', models.BooleanField(default=False)),
                ('time_offset', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('action_type', models.CharField(choices=[('tx_send_whatsapp', 'Send WhatsApp Message'), ('tx_send_push_notification', 'Send Push Notification'), ('send_email', 'Send Email'), ('send_sms', 'Send SMS'), ('trigger_webhook', 'HTTP Request'), ('add_to_mailchimp_list', 'Add contact to Mailchimp')], max_length=50)),
                ('audience_id', models.CharField(blank=True, max_length=255, null=True)),
                ('to_email', models.CharField(blank=True, max_length=250, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.IntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('run_time', models.DateTimeField()),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('run_logs', models.JSONField(blank=True, default=list, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledProcessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('process_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.processaction')),
                ('scheduled_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.scheduledjob')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledActionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.processaction')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.scheduledjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('sms_sent', 'SMS Sent'), ('email_sent', 'Email Sent'), ('process_job_run', 'Process Job Run'), ('process_job_cancelled', 'Process Job Cancelled')], max_length=200)),
                ('action_view_link', models.CharField(blank=True, max_length=350, null=True)),
                ('action_track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.scheduledjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
