# Generated by Django 4.2 on 2025-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.JSONField(default=dict)),
                ('setup_pages', models.JSONField(default=dict)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo')),
                ('business_information', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
