# Generated by Django 4.2 on 2025-03-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
