# Generated by Django 4.2 on 2025-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_customgroup_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
